#!name=菜鸟 · 广告与推广净化
#!desc=fmz200；广告、商品推广与问卷净化，保留取件及消息接口
#!author=奶思
#!category=奶思的模块
#!homepage=https://github.com/fmz200/wool_scripts
#!raw-url=https://raw.githubusercontent.com/Maxworkinghard/module/main/modules/CaiNiao.module
#!tg-channel=https://t.me/inaisi

[URL Rewrite]
# 支付宝-菜鸟
^https?:\/\/guide-acs\.m\.taobao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads - reject

[Map Local]
# 首页 好物推荐,商品推广,底部标签页,快递详情页,问卷调查,主页图标
^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.adkeyword\.get\.cn data-type=text data="{}" header="Content-Type:application/json"


^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.(batch\.show\.v2|index)\.cn data-type=text data="{}" header="Content-Type:application/json"

^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.nbopen\.miniapp\.recommend\.cpc\.cn data-type=text data="{}" header="Content-Type:application/json"

^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.nbmensa\.research\.researchservice\.(acquire|event|close)\.cn data-type=text data="{}" header="Content-Type:application/json"


# 发现页 数字角标 裹裹券
^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.com\.cainiao\.cnactivitycenter data-type=text data="{}" header="Content-Type:application/json"

^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.com\.cainiao\.cncreditmarket\.hit\.getactivityhit\.cn data-type=text data="{}" header="Content-Type:application/json"

^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.com\.cainiao\.longquan\.place\.getpageresourcecontent\.cn data-type=text data="{}" header="Content-Type:application/json"

[Script]

菜鸟裹裹 = type=http-response, pattern=^https?:\/\/cn-acs\.m\.cainiao\.com\/gw\/mtop\.cainiao\.guoguo\.nbnetflow\.ads\.m?show\.cn, script-path=https://raw.githubusercontent.com/Maxworkinghard/module/main/scripts/mirrors/05f68b57c8c15966-cainiao.js, requires-body=true, timeout=60


# 消息中心

[MITM]
hostname = %APPEND% cn-acs.m.cainiao.com, amdc.m.taobao.com
