#!name=YouTube
#!desc=YouTube 去广告、画中画(PiP)、后台播放 (Maasea)
#!author=Maasea
#!category=媒体影音

[Script]
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch|log_event|config))(\?(.*))?$,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://fastly.jsdelivr.net/gh/Maxworkinghard/module@main/scripts/youtube.response.js,argument="{"captionLang":"off","blockUpload":true,"blockImmersive":true,"blockShorts":false,"debug":false}"
youtube.request.init = type=http-request,pattern=^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&ack.*,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://fastly.jsdelivr.net/gh/Maxworkinghard/module@main/scripts/youtube.request.js,argument="{"captionLang":"off"}"
youtube.request.log_event = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/log_event,requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://fastly.jsdelivr.net/gh/Maxworkinghard/module@main/scripts/youtube.request.js

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com
