#!name=TikTokRegion · 免拔卡换区
#!desc=Keywos 请求换区；默认 US，可编辑 argument 为所需地区；可与 DailyAds 或 TikTokAds 搭配
#!author=Keywos
#!homepage=https://github.com/Keywos/rule
#!category=媒体影音

[Rule]
DOMAIN-KEYWORD,tiktokcdn,PROXY
DOMAIN-SUFFIX,byteoversea.com,PROXY
DOMAIN-SUFFIX,ibytedtos.com,PROXY
DOMAIN-SUFFIX,ipstatp.com,PROXY
DOMAIN-SUFFIX,muscdn.com,PROXY
DOMAIN-SUFFIX,musical.ly,PROXY
DOMAIN-SUFFIX,tik-tokapi.com,PROXY
DOMAIN-SUFFIX,tiktok.com,PROXY
DOMAIN-SUFFIX,tiktokcdn.com,PROXY
USER-AGENT,TikTok*,PROXY

[Script]
TikTokRegion.request = type=http-request,pattern=^https?:\/\/((tnc|dm).+\.[^\/]+\.com\/\w+\/v\d\/\?|.+\.(byteoversea|tiktokv).com\/.+(_region=CN&|&mcc_mnc=4)),script-path=https://raw.githubusercontent.com/Maxworkinghard/module/main/scripts/tk.js,timeout=20,argument=US

[MITM]
hostname = %APPEND% *.byteoversea.com, *.tik-tokapi.com, *.tiktokv.com
